_USER_PADDING_LEFT = 8
_USER_PADDING_TOP = 7
_USER_PADDING_RIGHT = 7

_USER_GRID_LEFT = 113
_USER_GRID_TOP = 355
_USER_GRID_RIGHT = 532
_USER_GRID_BOT = 770

_USER_GRID_WIDTH = _USER_GRID_RIGHT - _USER_GRID_LEFT
_USER_GRID_HEIGHT = _USER_GRID_BOT - _USER_GRID_TOP